### ISSUE TITLE
Trouble with `cargo build`

### ISSUE THREAD

**Issue by maemreyo** [mr-pascal/medium-rust-dockerize#1]
I had an error when trying to run your dockerfile
` => ERROR [builder  7/10] RUN cargo build --target x86_64-unknown-linux-musl --release                       76.5s
------                                                                                                             
 > [builder  7/10] RUN cargo build --target x86_64-unknown-linux-musl --release:                                   
#15 0.638     Updating crates.io index                                                                             
#15 62.62  Downloading crates ...                                                                                  
#15 64.39   Downloaded bytes v1.2.1
#15 64.41   Downloaded socket2 v0.4.7
#15 64.42   Downloaded atty v0.2.14
#15 64.46   Downloaded base64 v0.13.1
#15 64.48   Downloaded bitflags v1.3.2
#15 64.50   Downloaded cc v1.0.74
#15 64.50   Downloaded cfg-if v1.0.0
#15 64.55   Downloaded chrono v0.4.22
#15 64.55   Downloaded cron v0.10.1
#15 64.56   Downloaded dotenv v0.15.0
#15 64.63   Downloaded env_logger v0.9.1
#15 64.64   Downloaded fnv v1.0.7
#15 64.64   Downloaded foreign-types-shared v0.1.1
#15 64.64   Downloaded foreign-types v0.3.2
#15 64.65   Downloaded form_urlencoded v1.1.0
#15 64.65   Downloaded futures-channel v0.3.25
#15 64.65   Downloaded futures-sink v0.3.25
#15 64.65   Downloaded futures-core v0.3.25
#15 64.67   Downloaded futures-task v0.3.25
#15 64.70   Downloaded futures-util v0.3.25
#15 64.71   Downloaded h2 v0.3.15
#15 64.72   Downloaded gql_client v1.0.7
#15 64.72   Downloaded hashbrown v0.12.3
#15 64.72   Downloaded getrandom v0.2.8
#15 64.73   Downloaded http-body v0.4.5
#15 64.73   Downloaded humantime v2.1.0
#15 64.73   Downloaded httparse v1.8.0
#15 64.73   Downloaded http v0.2.8
#15 64.75   Downloaded hyper v0.14.22
#15 64.76   Downloaded iana-time-zone v0.1.53
#15 64.76   Downloaded hyper-tls v0.5.0
#15 64.77   Downloaded indexmap v1.9.1
#15 64.78   Downloaded itoa v1.0.4
#15 64.78   Downloaded ipnet v2.5.0
#15 64.83   Downloaded lock_api v0.4.9
#15 64.83   Downloaded log v0.4.17
#15 64.84   Downloaded memchr v2.5.0
#15 64.84   Downloaded mime v0.3.16
#15 64.85   Downloaded minimal-lexical v0.2.1
#15 64.85   Downloaded native-tls v0.2.11
#15 64.86   Downloaded mio v0.8.5
#15 64.86   Downloaded openssl-macros v0.1.0
#15 64.86   Downloaded openssl-probe v0.1.5
#15 64.87   Downloaded once_cell v1.16.0
#15 64.87   Downloaded pin-utils v0.1.0
#15 64.87   Downloaded pkg-config v0.3.26
#15 64.87   Downloaded quote v1.0.21
#15 64.88   Downloaded pin-project-lite v0.2.9
#15 64.88   Downloaded parking_lot_core v0.9.4
#15 64.89   Downloaded regex v1.6.0
#15 64.90   Downloaded parking_lot v0.12.1
#15 64.90   Downloaded num_cpus v1.13.1
#15 64.90   Downloaded num-traits v0.2.15
#15 64.91   Downloaded num-derive v0.3.3
#15 64.91   Downloaded nom v7.1.1
#15 64.92   Downloaded reqwest v0.11.12
#15 64.93   Downloaded serde v1.0.147
#15 64.93   Downloaded signal-hook-registry v1.4.0
#15 64.93   Downloaded serde_urlencoded v0.7.1
#15 64.94   Downloaded smallvec v1.10.0
#15 64.94   Downloaded serde_derive v1.0.147
#15 64.94   Downloaded scopeguard v1.1.0
#15 65.08   Downloaded syn v1.0.103
#15 65.09   Downloaded tinyvec v1.6.0
#15 65.09   Downloaded time v0.1.44
#15 65.10   Downloaded termcolor v1.1.3
#15 65.10   Downloaded tinyvec_macros v0.1.0
#15 65.10   Downloaded tokio-cron-scheduler v0.8.1
#15 65.11   Downloaded num-integer v0.1.45
#15 65.11   Downloaded httpdate v1.0.2
#15 65.11   Downloaded openssl v0.10.42
#15 65.12   Downloaded ryu v1.0.11
#15 65.13   Downloaded proc-macro2 v1.0.47
#15 65.13   Downloaded slab v0.4.7
#15 65.13   Downloaded tokio-macros v1.8.0
#15 65.13   Downloaded serde_json v1.0.87
#15 65.14   Downloaded tracing-core v0.1.30
#15 65.15   Downloaded unicode-ident v1.0.5
#15 65.15   Downloaded url v2.3.1
#15 65.15   Downloaded want v0.3.0
#15 65.16   Downloaded uuid v1.2.1
#15 65.16   Downloaded try-lock v0.2.3
#15 65.16   Downloaded tokio-native-tls v0.3.0
#15 65.16   Downloaded anyhow v1.0.66
#15 65.17   Downloaded aho-corasick v0.7.19
#15 65.17   Downloaded unicode-normalization v0.1.22
#15 65.18   Downloaded autocfg v1.1.0
#15 65.18   Downloaded unicode-bidi v0.3.8
#15 65.18   Downloaded tracing-attributes v0.1.23
#15 65.19   Downloaded regex-syntax v0.6.27
#15 65.20   Downloaded tracing v0.1.37
#15 65.20   Downloaded tower-service v0.3.2
#15 65.20   Downloaded tokio-util v0.7.4
#15 65.21   Downloaded percent-encoding v2.2.0
#15 65.21   Downloaded idna v0.3.0
#15 65.22   Downloaded tokio v1.21.2
#15 65.25   Downloaded encoding_rs v0.8.31
#15 65.28   Downloaded libc v0.2.137
#15 65.31   Downloaded openssl-sys v0.9.77
#15 65.40    Compiling autocfg v1.1.0
#15 65.40    Compiling libc v0.2.137
#15 65.40    Compiling proc-macro2 v1.0.47
#15 65.40    Compiling unicode-ident v1.0.5
#15 65.40    Compiling quote v1.0.21
#15 65.57    Compiling syn v1.0.103
#15 65.83    Compiling cfg-if v1.0.0
#15 65.87    Compiling memchr v2.5.0
#15 65.88    Compiling log v0.4.17
#15 65.89    Compiling once_cell v1.16.0
#15 65.94    Compiling pin-project-lite v0.2.9
#15 65.99    Compiling parking_lot_core v0.9.4
#15 66.06    Compiling bytes v1.2.1
#15 66.17    Compiling smallvec v1.10.0
#15 66.21    Compiling pkg-config v0.3.26
#15 66.26    Compiling cc v1.0.74
#15 66.42    Compiling scopeguard v1.1.0
#15 66.49    Compiling futures-core v0.3.25
#15 66.56    Compiling itoa v1.0.4
#15 66.76    Compiling futures-task v0.3.25
#15 66.81    Compiling openssl v0.10.42
#15 66.94    Compiling futures-util v0.3.25
#15 67.10    Compiling foreign-types-shared v0.1.1
#15 67.18    Compiling serde_derive v1.0.147
#15 67.24    Compiling fnv v1.0.7
#15 67.27    Compiling futures-sink v0.3.25
#15 67.27    Compiling serde v1.0.147
#15 67.37    Compiling tinyvec_macros v0.1.0
#15 67.41    Compiling futures-channel v0.3.25
#15 67.48    Compiling hashbrown v0.12.3
#15 67.54    Compiling pin-utils v0.1.0
#15 67.56    Compiling httparse v1.8.0
#15 67.69    Compiling bitflags v1.3.2
#15 67.73    Compiling native-tls v0.2.11
#15 67.73    Compiling percent-encoding v2.2.0
#15 67.80    Compiling try-lock v0.2.3
#15 67.93    Compiling openssl-probe v0.1.5
#15 67.94    Compiling httpdate v1.0.2
#15 68.06    Compiling unicode-bidi v0.3.8
#15 68.10    Compiling tower-service v0.3.2
#15 68.21    Compiling serde_json v1.0.87
#15 68.21    Compiling encoding_rs v0.8.31
#15 68.39    Compiling ryu v1.0.11
#15 68.49    Compiling minimal-lexical v0.2.1
#15 68.56    Compiling iana-time-zone v0.1.53
#15 68.61    Compiling anyhow v1.0.66
#15 68.79    Compiling base64 v0.13.1
#15 68.92    Compiling mime v0.3.16
#15 69.02    Compiling regex-syntax v0.6.27
#15 69.16    Compiling ipnet v2.5.0
#15 69.44    Compiling tokio-cron-scheduler v0.8.1
#15 69.74    Compiling humantime v2.1.0
#15 69.74    Compiling termcolor v1.1.3
#15 69.80    Compiling dotenv v0.15.0
#15 70.68    Compiling lock_api v0.4.9
#15 70.72    Compiling tokio v1.21.2
#15 71.09    Compiling slab v0.4.7
#15 71.14    Compiling indexmap v1.9.1
#15 71.20    Compiling num-traits v0.2.15
#15 71.44    Compiling num-integer v0.1.45
#15 71.50    Compiling tracing-core v0.1.30
#15 71.58    Compiling foreign-types v0.3.2
#15 71.59    Compiling http v0.2.8
#15 71.72    Compiling tinyvec v1.6.0
#15 71.94    Compiling openssl-sys v0.9.77
#15 72.67    Compiling form_urlencoded v1.1.0
#15 74.79    Compiling http-body v0.4.5
#15 75.02    Compiling unicode-normalization v0.1.22
#15 75.21 error: failed to run custom build command for `openssl-sys v0.9.77`
#15 75.21 
#15 75.21 Caused by:
#15 75.21   process didn't exit successfully: `/usr/src/git-stats-bot/target/release/build/openssl-sys-c68161153bf7c778/build-script-main` (exit status: 101)
#15 75.21   --- stdout
#15 75.21   cargo:rustc-cfg=const_fn
#15 75.21   cargo:rustc-cfg=openssl
#15 75.21   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR
#15 75.21   X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_LIB_DIR unset
#15 75.21   cargo:rerun-if-env-changed=OPENSSL_LIB_DIR
#15 75.21   OPENSSL_LIB_DIR unset
#15 75.21   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR
#15 75.21   X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_INCLUDE_DIR unset
#15 75.21   cargo:rerun-if-env-changed=OPENSSL_INCLUDE_DIR
#15 75.21   OPENSSL_INCLUDE_DIR unset
#15 75.21   cargo:rerun-if-env-changed=X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR
#15 75.21   X86_64_UNKNOWN_LINUX_MUSL_OPENSSL_DIR unset
#15 75.21   cargo:rerun-if-env-changed=OPENSSL_DIR
#15 75.21   OPENSSL_DIR unset
#15 75.21   cargo:rerun-if-env-changed=OPENSSL_NO_PKG_CONFIG
#15 75.21   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64-unknown-linux-musl
#15 75.21   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS_x86_64_unknown_linux_musl
#15 75.21   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_ALLOW_CROSS
#15 75.21   cargo:rerun-if-env-changed=PKG_CONFIG_ALLOW_CROSS
#15 75.21   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64-unknown-linux-musl
#15 75.21   cargo:rerun-if-env-changed=PKG_CONFIG_x86_64_unknown_linux_musl
#15 75.21   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG
#15 75.21   cargo:rerun-if-env-changed=PKG_CONFIG
#15 75.21   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64-unknown-linux-musl
#15 75.21   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR_x86_64_unknown_linux_musl
#15 75.21   cargo:rerun-if-env-changed=TARGET_PKG_CONFIG_SYSROOT_DIR
#15 75.21   cargo:rerun-if-env-changed=PKG_CONFIG_SYSROOT_DIR
#15 75.21   run pkg_config fail: "pkg-config has not been configured to support cross-compilation.\n\nInstall a sysroot for the target platform and configure it via\nPKG_CONFIG_SYSROOT_DIR and PKG_CONFIG_PATH, or install a\ncross-compiling wrapper for pkg-config and set it via\nPKG_CONFIG environment variable."
#15 75.21 
#15 75.21   --- stderr
#15 75.21   thread 'main' panicked at '
#15 75.21 
#15 75.21   Could not find directory of OpenSSL installation, and this `-sys` crate cannot
#15 75.21   proceed without this knowledge. If OpenSSL is installed and this crate had
#15 75.21   trouble finding it,  you can set the `OPENSSL_DIR` environment variable for the
#15 75.21   compilation process.
#15 75.21 
#15 75.21   Make sure you also have the development packages of openssl installed.
#15 75.21   For example, `libssl-dev` on Ubuntu or `openssl-devel` on Fedora.
#15 75.21 
#15 75.21   If you're in a situation where you think the directory *should* be found
#15 75.21   automatically, please open a bug at https://github.com/sfackler/rust-openssl
#15 75.21   and include information about your system as well as this message.
#15 75.21 
#15 75.21   $HOST = aarch64-unknown-linux-gnu
#15 75.21   $TARGET = x86_64-unknown-linux-musl
#15 75.21   openssl-sys = 0.9.77
#15 75.21 
#15 75.21   ', /usr/local/cargo/registry/src/github.com-1ecc6299db9ec823/openssl-sys-0.9.77/build/find_normal.rs:191:5
#15 75.21   note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
#15 75.21 warning: build failed, waiting for other jobs to finish...
------
executor failed running [/bin/sh -c cargo build --target x86_64-unknown-linux-musl --release]: exit code: 101`

**Comment by mr-pascal** [comment]
Hi @maemreyo ,
thanks for your interest in this repository.
I just cloned the repo and run the command to build the container

`docker build -t rust-web-alpine .`

And everything works fine on my machine 🤔 
![image](https://user-images.githubusercontent.com/4190798/200128231-afed1a2d-7ce7-4a9a-8e50-2c4e80b89bf5.png)


Do you have any colleagues/friends that could check it out also on their machine?
Do you have any specific configuration for your building images on your machine?

**Comment by maemreyo** [comment]
It's so weird.
I dont have any friends to check @@!

**Comment by mr-pascal** [comment]
Really weird.

- Do you have any issues with building any other images?
- Do you have a "clean" copy of this repo, or have you added any changes?
- Have you tried using th `full` docker image instead of the slim variant `rust:1.61.0-slim` ?

**Comment by mr-pascal** [comment]
@maemreyo 
After digging quite deep and investing a lot of hours I might have found a solution to your problem after facing the same with trying to compile `actix-web` in my Dockerfile.

It helped to add the following to my `Cargo.toml` dependencies
```toml
openssl = { version = "10.43", features = ["vendored"] } 
```

**Comment by mr-pascal** [comment]
@maemreyo 
you can also find a working example here: https://github.com/mr-pascal/rust-demo-webserver/blob/main/Dockerfile

**Comment by mr-pascal** [comment]
Close, since no response.
